language: python
group: travis_latest
dist: xenial

cache: pip

matrix:
    include:
    - name: "Linux Python 3.5"
      os: linux
      python: 3.5
      setup: pip install ".[rekall]"

    - name: "Linux Python 3.6"
      os: linux
      python: 3.6
      setup: pip install ".[rekall]"

    - name: "Linux Python 3.7"
      os: linux
      python: 3.7
      setup: pip install ".[rekall]"

    - name: "Windows Python 3.5"
      os: windows
      language: sh
      setup: pip install ".[rekall]"
      before_install:
      - choco install python3 --version 3.5.6
      - export PATH="/c/Python35:/c/Python35/Scripts:$PATH"

    - name: "Windows Python 3.6"
      os: windows
      language: sh
      setup: pip install .
      before_install:
        - choco install python3 --version 3.6.8
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"

    - name: "Windows Python 3.7"
      os: windows
      language: sh
      setup: pip install .
      before_install:
          - choco install python3 --version 3.7.0
          - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

    - name: "MacOSX Python 3.6"
      os: osx
      python: 3.6
      language: sh
      install: pip3 install -e .[tests]

    - name: "MacOSX Python 3.7"
      os: osx
      python: 3.7
      language: sh
      install: pip3 install -e .[tests]

script: mkdir -p data && pytest
